name: Build Binaries

on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build Cross-Platform Binaries
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for tags and branches

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"

      - name: Run tests
        run: go test -v ./...

      - name: Build binaries for multiple platforms
        run: |
          mkdir -p bin
          platforms=("linux amd64" "linux arm64" "darwin amd64" "darwin arm64" "windows amd64")

          for platform in "${platforms[@]}"; do
            os=$(echo $platform | cut -d ' ' -f1)
            arch=$(echo $platform | cut -d ' ' -f2)
            echo "Building for $os/$arch..."
            make build GOOS=$os GOARCH=$arch
          done

      - name: List generated binaries
        run: ls -la bin/

      - name: Upload binaries as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: mcp-kafka-binaries
          path: bin/

  release:
    name: Create Release
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: mcp-kafka-binaries
          path: bin

      - name: List artifacts
        run: ls -la bin/

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: bin/*
          generate_release_notes: true
